Repository Just-Clover/YOUng-chat-backend, pull requests merged in 2024-02, with the labels that each got.

#230 외부 Rabbit ec2 적용 기본 값으로 수정
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor

#231 dev 로그 수정
  src/main/resources/logback-spring.xml
Labels: refactor

#233 RabbitMQ host 수정
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor

#236 RabbitMQ v2
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor

#238 [#237] Refactor: ChatRoom entity 테이블 명 chatroom 지정
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoom.java
Labels: refactor

#239 RabbitMQ v3
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor

#240 Websocket handler 주석 처리
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/main/java/com/clover/youngchat/global/security/FilterChannelInterceptor.java
Labels: refactor

#241 Update CD.yml: seperate DEV EC2
  .github/workflows/CD.yml
Labels: chore

#242 Create mainCD.yml: main dockercompose cd파일 분리
  .github/workflows/mainCD.yml
Labels: chore

#245 알림 반환 데이터에 ChatRoomId 추가
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatAlertRes.java
Labels: refactor

#248 Main CD 변경
  .github/workflows/mainCD.yml
Labels: chore

#250 ECR, CodeDeploy를 사용한 CD2 yml 파일 세팅
  .github/workflows/CD.yml
  .github/workflows/CD_V1.yml
  .github/workflows/CD_V2.yml
  .github/workflows/CI.yml
  .github/workflows/mainCD.yml
  appspec.yml
Labels: chore

#252 ChatList Cache 적용
  src/main/java/com/clover/youngchat/domain/chat/dto/response/ChatRes.java
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/constant/ChatRoomConstant.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomPaginationDetailGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/clover/youngchat/global/config/RedisCacheConfig.java
  src/main/java/com/clover/youngchat/global/response/RestSlice.java
Labels: feat, refactor

#255 Cache 제거
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: refactor

#257 Feat/db
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/service/command/ChatCommandService.java
  src/main/java/com/clover/youngchat/domain/chatroom/constant/ChatRoomConstant.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/command/ChatRoomCommandService.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/query/ChatRoomQueryService.java
  src/main/java/com/clover/youngchat/domain/friend/controller/FriendController.java
  src/main/java/com/clover/youngchat/domain/friend/service/command/FriendCommandService.java
  src/main/java/com/clover/youngchat/domain/friend/service/query/FriendQueryService.java
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/service/command/UserCommandService.java
  src/main/java/com/clover/youngchat/domain/user/service/query/UserQueryService.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/main/java/com/clover/youngchat/global/security/FilterChannelInterceptor.java
  src/test/java/com/clover/youngchat/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/com/clover/youngchat/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/clover/youngchat/domain/friend/service/FriendServiceTest.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
Labels: feat, refactor

#259 Database 읽기 / 쓰기 분리
  src/main/java/com/clover/youngchat/global/datasource/DataSourceType.java
  src/main/java/com/clover/youngchat/global/datasource/TransactionRoutingDataSource.java
  src/main/java/com/clover/youngchat/global/datasource/TransactionRoutingDataSourceConfig.java
  src/main/java/com/clover/youngchat/global/security/UserDetailsServiceImpl.java
Labels: feat

#263 채팅 삭제 HTTP 통신에서 Websocket으로 변경
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/dto/request/ChatDeleteReq.java
  src/main/java/com/clover/youngchat/domain/chat/service/command/ChatCommandService.java
  src/test/java/com/clover/youngchat/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
Labels: feat, refactor, test

#264 Docs: README update
  README.md
Labels: docs

#266 Feature/readme
  README.md
Labels: docs

#270 Mongo
  .gitignore
  build.gradle.kts
Labels: chore

#272 Mail 전송 비동기 처리
  src/main/java/com/clover/youngchat/global/config/AsyncConfig.java
  src/main/java/com/clover/youngchat/global/email/EmailUtil.java
Labels: refactor

#274 S3 이미지 업로드 리사이징 구현
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/user/service/command/UserCommandService.java
  src/main/java/com/clover/youngchat/global/config/AsyncConfig.java
  src/main/java/com/clover/youngchat/global/s3/CustomMultipartFile.java
  src/main/java/com/clover/youngchat/global/s3/S3Util.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
Labels: feat, refactor, test, chore
