Repository Just-Clover/YOUng-chat-backend, pull requests merged in 2024-01, with the labels that each got.

#2 Chore: update pull_request_template
  .github/pull_request_template.md
Labels: chore

#3 [#1] Chore: create Issue template
  .github/ISSUE_TEMPLATE /issue_request.md
Labels: chore

#4 [#1] Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#5 Chore: issue template 재정의
  .github/ISSUE_TEMPLATE /issue_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#7 CI 파일 추가
  .github/workflows/ci-workflow.yml
Labels: chore

#8 Test: buildTest
  .github/workflows/ci-workflow.yml
  .gitignore
  src/main/resources/application.properties
  src/test/java/com/clover/youngchat/YoungChatApplicationTests.java
Labels: test, chore

#15 Global Exception, Custom Response 구현
  src/main/java/com/clover/youngchat/global/common/ErrorRes.java
  src/main/java/com/clover/youngchat/global/common/InvalidErrorRes.java
  src/main/java/com/clover/youngchat/global/exception/GlobalException.java
  src/main/java/com/clover/youngchat/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/main/java/com/clover/youngchat/global/response/RestResponse.java
Labels: feat

#16 토큰 발급 로직 및 Config 적용
  build.gradle.kts
  src/main/java/com/clover/youngchat/global/jwt/JwtUtil.java
  src/main/java/com/clover/youngchat/global/security/SecurityConfig.java
Labels: feat, docs

#24 Redis 환경 구성 & 필터 로직 구현
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserLoginReq.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserSignupReq.java
  src/main/java/com/clover/youngchat/domain/user/repository/UserRepository.java
  src/main/java/com/clover/youngchat/global/config/RedisConfig.java
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/main/java/com/clover/youngchat/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/clover/youngchat/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/clover/youngchat/global/jwt/JwtUtil.java
  src/main/java/com/clover/youngchat/global/redis/RedisUtil.java
  src/main/java/com/clover/youngchat/global/security/UserDetailsImpl.java
  src/main/java/com/clover/youngchat/global/security/UserDetailsServiceImpl.java
  src/test/java/com/clover/youngchat/SampleTest.java
Labels: feat, refactor, test, chore

#26 회원가입 Api 테스트코드 작성 & UserConstant 분리
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserSignupReq.java
  src/test/java/com/clover/youngchat/domain/BaseMvcTest.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
  src/test/java/com/clover/youngchat/global/MockSpringSecurityFilter.java
  src/test/java/test/UserTest.java
Labels: test

#29 프로필 수정 기능 구현
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserProfileEditReq.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserProfileEditRes.java
  src/main/java/com/clover/youngchat/domain/user/entity/User.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
Labels: feat

#33 친구 도메인 구현 및 추가 기능 API 구현 / 테스트 코드 작성
  .gitignore
  src/main/java/com/clover/youngchat/domain/friend/controller/FriendController.java
  src/main/java/com/clover/youngchat/domain/friend/dto/response/FriendAddRes.java
  src/main/java/com/clover/youngchat/domain/friend/entity/Friend.java
  src/main/java/com/clover/youngchat/domain/friend/entity/FriendPK.java
  src/main/java/com/clover/youngchat/domain/friend/repository/FriendRepository.java
  src/main/java/com/clover/youngchat/domain/friend/service/FriendService.java
  src/main/java/com/clover/youngchat/domain/user/repository/UserRepository.java
  src/main/java/com/clover/youngchat/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/clover/youngchat/global/jwt/JwtUtil.java
  src/test/java/com/clover/youngchat/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/clover/youngchat/domain/friend/repository/FriendRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/friend/service/FriendServiceTest.java
Labels: feat, refactor, test

#38 프로필 사진 업로드 S3 적용
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserProfileEditReq.java
  src/main/java/com/clover/youngchat/domain/user/entity/User.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/main/java/com/clover/youngchat/global/config/S3Config.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/main/java/com/clover/youngchat/global/s3/S3Util.java
Labels: feat

#41 채팅방 추가 기능
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/ChatRoomCreateReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomCreateRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatUser.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatUserPK.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: feat

#42 이메일 인증 작업 및 회원가입 일부 로직 변경
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserEmailAuthCheckReq.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserEmailAuthReq.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserEmailAuthCheckRes.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserEmailAuthRes.java
  src/main/java/com/clover/youngchat/domain/user/entity/EmailAuth.java
  src/main/java/com/clover/youngchat/domain/user/repository/EmailAuthRepository.java
  src/main/java/com/clover/youngchat/domain/user/service/EmailAuthService.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/main/java/com/clover/youngchat/global/config/EmailConfig.java
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
  src/main/java/com/clover/youngchat/global/email/EmailUtil.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/main/resources/templates/email.html
  src/test/java/com/clover/youngchat/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/user/service/EmailAuthServiceTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
  src/test/java/com/clover/youngchat/global/email/EmailUtilTest.java
  src/test/java/test/EmailAuthTest.java
Labels: feat, refactor, test

#46 채팅방 수정 기능 구현
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/ChatRoomEditReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomEditRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatUser.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
Labels: feat

#49 친구 검색 기능 API 구현
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/friend/controller/FriendController.java
  src/main/java/com/clover/youngchat/domain/friend/dto/response/FriendGetListRes.java
  src/main/java/com/clover/youngchat/domain/friend/dto/response/FriendGetSearchListRes.java
  src/main/java/com/clover/youngchat/domain/friend/repository/FriendRepository.java
  src/main/java/com/clover/youngchat/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/friend/service/FriendService.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserLoginReq.java
  src/main/java/com/clover/youngchat/domain/user/repository/UserRepository.java
  src/main/java/com/clover/youngchat/global/config/QueryDslConfig.java
  src/test/java/com/clover/youngchat/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/clover/youngchat/domain/friend/repository/FriendRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/friend/service/FriendServiceTest.java
  src/test/java/com/clover/youngchat/domain/user/repository/UserRepositoryTest.java
Labels: feat, refactor, test, chore

#48 채팅방 나가기 기능 구현
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomLeaveRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
Labels: feat

#50 채팅 입력 Api 기능 구현
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/dto/request/ChatCreateReq.java
  src/main/java/com/clover/youngchat/domain/chat/dto/response/ChatCreateRes.java
  src/main/java/com/clover/youngchat/domain/chat/entity/Chat.java
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepository.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatUserRepository.java
  src/test/java/com/clover/youngchat/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/clover/youngchat/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/test/ChatRoomTest.java
  src/test/java/test/ChatTest.java
  src/test/java/test/ChatUserTest.java
Labels: feat, test

#54 채팅방 목록 조회 기능 추가
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepository.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomListGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoomUser.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoomUserPK.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/test/ChatUserTest.java
Labels: feat

#56 채팅 삭제 기능 구현
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/dto/response/ChatDeleteRes.java
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepository.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/test/java/com/clover/youngchat/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/clover/youngchat/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
Labels: feat, test

#57 채팅방 상세 조회 API 구현
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomAndLastChatGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomDetailGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: feat

#62 프로필 조회 테스트 코드
  src/main/java/com/clover/youngchat/global/exception/GlobalExceptionHandler.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
  src/test/java/test/UserTest.java
Labels: test

#64 프로필 수정 테스트 코드 구현
  src/main/resources/images/imdie.png
  src/main/resources/images/profileImage.png
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
  src/test/java/test/UserTest.java
Labels: test

#67 CORS 설정
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserEmailAuthReq.java
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
Labels: feat, refactor

#70 비밀번호변경 Dto, 회원가입 Dto 수정
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserSignupReq.java
  src/main/java/com/clover/youngchat/domain/user/dto/request/UserUpdatePasswordReq.java
Labels: refactor, fix

#72 테스트코드 수정
  src/test/java/com/clover/youngchat/domain/auth/service/EmailAuthServiceTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
Labels: test

#74 Securtiy Exception Handler
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
  src/main/java/com/clover/youngchat/global/exception/FilterExceptionHandler.java
  src/main/java/com/clover/youngchat/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/clover/youngchat/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/clover/youngchat/global/response/RestResponse.java
Labels: feat, refactor

#76 채팅방 제목 처리 및 채팅 삭제 처리 개선
  src/main/java/com/clover/youngchat/domain/chat/constant/ChatConstant.java
  src/main/java/com/clover/youngchat/domain/chat/entity/Chat.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/constant/ChatRoomConstant.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/ChatRoomCreateReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/ChatRoomEditReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoomUser.java
  src/main/java/com/clover/youngchat/domain/friend/entity/Friend.java
  src/main/java/com/clover/youngchat/domain/sample/controller/SampleController.java
  src/main/java/com/clover/youngchat/domain/sample/dto/request/SampleSaveReq.java
  src/main/java/com/clover/youngchat/domain/sample/dto/response/SampleGetRes.java
  src/main/java/com/clover/youngchat/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/com/clover/youngchat/domain/sample/entity/Sample.java
  src/main/java/com/clover/youngchat/domain/sample/repository/SampleRepository.java
  src/main/java/com/clover/youngchat/domain/sample/service/SampleService.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
Labels: refactor, rename

#77 채팅이 없어도 방 목록은 보이도록 처리 및 Chat entity 수정
  src/main/java/com/clover/youngchat/domain/chat/entity/Chat.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomAndLastChatGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: refactor

#79 채팅방 나가기 테스트 코드 추가
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/test/ChatRoomUserTest.java
Labels: test

#82 프로필 조회 로직 변경
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
Labels: refactor, test

#83 채팅방 수정 테스트 코드 추가
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
Labels: test

#84 채팅방 목록 조회 테스트 코드 추가
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/test/ChatRoomUserTest.java
  src/test/java/test/ChatTest.java
Labels: test, clean

#87 친구 ID 값 반환 추가
  src/main/java/com/clover/youngchat/domain/friend/dto/response/FriendGetListRes.java
  src/main/java/com/clover/youngchat/domain/friend/service/FriendService.java
Labels: refactor

#89 [#88] Refactor: 유저 조회시 본인을 조회할 경우 dto에 이메일도 반환
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserProfileGetRes.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
Labels: refactor

#91 채팅방 조회시 ID 값 추가 반환
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomAndLastChatGetRes.java
Labels: refactor

#96 Refactor: 채팅방 상세목록 조회시 채팅Res에 username대신 userId로 변경
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomDetailGetRes.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
Labels: refactor

#99 사용자 검색 API 기능 구현
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserProfileSearchRes.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
  src/test/java/com/clover/youngchat/domain/user/service/UserServiceTest.java
Labels: feat, test

#101 RedisTemplate 버그 수정
  src/main/java/com/clover/youngchat/global/config/RedisConfig.java
  src/main/java/com/clover/youngchat/global/redis/RedisUtil.java
Labels: refactor, fix

#103 채팅방 상세 조회 DTO 필드 추가
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomDetailGetRes.java
Labels: refactor

#115 채팅방 생성 로직 수정
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomCreateRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: refactor

#116 채팅방 생성 로직 및 reqDto 수정
  src/main/java/com/clover/youngchat/domain/chat/entity/Chat.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/ChatRoomCreateReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomCreateRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomDetailGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/entity/ChatRoomUser.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
  src/test/java/test/ChatRoomTest.java
Labels: refactor, fix, test

#129 사용자 프로필 응답 DTO 값 추가
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserProfileSearchRes.java
Labels: refactor

#131 healthCheck Test
  src/main/java/com/clover/youngchat/domain/model/controller/HealthCheckController.java
  src/main/java/com/clover/youngchat/domain/model/dto/HealthRes.java
Labels: chore

#132 healthCheck Test
  src/main/java/com/clover/youngchat/domain/model/controller/HealthCheckController.java
Labels: chore

#133 healthCheck Security cofig 추가
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
Labels: chore

#135 정규식 재작성
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
Labels: refactor, fix

#139 사용자 이름 정규식 숫자 포함
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
Labels: fix

#141 타임존 설정 추가
  src/main/java/com/clover/youngchat/YoungChatApplication.java
Labels: feat

#143 친구 검색 응답 dto에 Id 필드 추가
  src/main/java/com/clover/youngchat/domain/friend/dto/response/FriendGetSearchListRes.java
  src/main/java/com/clover/youngchat/domain/friend/repository/FriendRepositoryImpl.java
Labels: refactor

#145 UT 피드백 적용 - 정규식, 친구추가API 예외처리, S3 jpeg 업로드
  src/main/java/com/clover/youngchat/domain/friend/service/FriendService.java
  src/main/java/com/clover/youngchat/domain/user/constant/UserConstant.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/main/java/com/clover/youngchat/global/exception/ResultCode.java
  src/test/java/com/clover/youngchat/domain/user/controller/valid/UserValidTest.java
  src/test/java/test/UserTest.java
Labels: refactor

#147 중복 이메일 체크 Api 구현
  src/main/java/com/clover/youngchat/domain/user/controller/UserController.java
  src/main/java/com/clover/youngchat/domain/user/dto/response/UserEmailCheckRes.java
  src/main/java/com/clover/youngchat/domain/user/service/UserService.java
  src/test/java/com/clover/youngchat/domain/user/controller/UserControllerTest.java
Labels: feat

#152 채팅방 목록조회 Dto LastChatDeleted 추가
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomAndLastChatGetRes.java
Labels: refactor

#156 웹소켓 적용
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/dto/request/ChatCreateReq.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/global/config/SecurityConfig.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/main/java/com/clover/youngchat/global/security/FilterChannelInterceptor.java
  src/test/java/com/clover/youngchat/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
Labels: feat

#169 Create appspec.yml
  appspec.yml
Labels: chore

#170 Update CD_V2.yml : deploy script 파일 수정
  .github/workflows/CD_V2.yml
Labels: chore

#176 RabbitMq 적용
  build.gradle.kts
  src/main/java/com/clover/youngchat/domain/chat/controller/ChatController.java
  src/main/java/com/clover/youngchat/domain/chat/dto/response/ChatRes.java
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/global/config/RabbitConfig.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/test/java/com/clover/youngchat/domain/chat/service/ChatServiceTest.java
Labels: feat, refactor, test

#180 Websocket 및 Rabbitmq config Host 설정추가
  src/main/java/com/clover/youngchat/global/config/RabbitConfig.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor

#188 ResponseDto Date타입 역직렬화 핸들링
  src/main/java/com/clover/youngchat/domain/chat/dto/response/ChatRes.java
Labels: refactor

#190 [#189] Chore: Docker compose 명령어 수정 및 CD 실행 조건 변경
  .github/workflows/CD.yml
  .github/workflows/CD_V2.yml
Labels: chore

#192 Docker compose 파일 및 CD 파일 수정
  .github/workflows/CD.yml
  docker-compose.yml
Labels: chore

#201 메세지 보냈을 때 알림 기능 추가
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
Labels: feat

#204 CD docker compose pull 제거
  .github/workflows/CD.yml
Labels: chore

#205 [#193] Chore: docker compose yml rabbitmq logs environment 추가
  docker-compose.yml
Labels: chore

#206 [#193] Chore: docker compose yml rabbitmq logs 파일 경로 수정
  docker-compose.yml
Labels: chore

#207 rabbitmq 로그 디렉토리 수정
  docker-compose.yml
Labels: chore

#210 [#193] Chore: docker compose network 추가
  docker-compose.yml
Labels: chore

#212 [#211] Fix: messageBroker relayhost 지정
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: fix

#214 [#193] Chore: docker compose yml stomp plugin 활성화 코드 추가
  docker-compose.yml
Labels: chore

#215 [#193] Chore: docker compose yml rabbitmq user 변경
  docker-compose.yml
Labels: chore

#216 [#153] Chore: CD 동작기준 수정(dev >> main)
  .github/workflows/CD.yml
Labels: chore

#217 Chore: Develop to Main
  .github/workflows/CD.yml
  .github/workflows/CD_V2.yml
  docker-compose.yml
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: chore

#219 알림 보내기 내부 Query로직 개선
  src/main/java/com/clover/youngchat/domain/chat/service/ChatService.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatAlertRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
Labels: refactor

#221 채팅방 상세조회 페이지네이션 역순으로 변경
  src/main/java/com/clover/youngchat/domain/chat/repository/ChatRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
Labels: refactor, rename

#224 로깅 처리
  .gitignore
  src/main/java/com/clover/youngchat/global/aop/LogAop.java
  src/main/java/com/clover/youngchat/global/security/FilterChannelInterceptor.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: feat, refactor, chore

#222 1:1 채팅방 생성시 로직 개선 및 QueryDsl >> JPQL로 수정
  src/main/java/com/clover/youngchat/domain/chatroom/constant/ChatRoomConstant.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/GroupChatRoomCreateReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/request/PersonalChatRoomCreateReq.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/GroupChatRoomCreateRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/PersonalChatRoomCreateRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepository.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/test/java/com/clover/youngchat/domain/chatRoom/controller/ChatRoomControllerTest.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
Labels: refactor

#227 Update CD.yml: docker compose 제거
  .github/workflows/CD.yml
Labels: chore

#228 RabbitMQ 설정 변경
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
  src/main/resources/logback-spring.xml
Labels: refactor

#225 [#220] 채팅방 목록 조회 커서 기반 페이지네이션 적용
  src/main/java/com/clover/youngchat/domain/chatroom/constant/ChatRoomConstant.java
  src/main/java/com/clover/youngchat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/clover/youngchat/domain/chatroom/dto/response/ChatRoomAndLastChatGetRes.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryCustom.java
  src/main/java/com/clover/youngchat/domain/chatroom/repository/ChatRoomUserRepositoryImpl.java
  src/main/java/com/clover/youngchat/domain/chatroom/service/ChatRoomService.java
  src/test/java/com/clover/youngchat/domain/chatRoom/service/ChatRoomServiceTest.java
Labels: feat

#229 외부 Rabbit ec2 적용
  src/main/java/com/clover/youngchat/global/config/WebsocketConfig.java
Labels: refactor
